title: 'Expenses: Spending Tracker'
author: pixyzehn
description: Expenses has been crafted to keep track of your spending effortlessly, with useful features in a simple, intuitive interface.
url: https://getexpenses.app
timezone: Asia/Tokyo

links:
  app_store: https://apple.co/3rUeBBK
  app_store_review: https://apps.apple.com/app/id1492055171/?action=write-review
  twitter: https://twitter.com/expensesapp
  developer: https://pixyzehn.com
  jekyll: https://jekyllrb.com

sass:
  style: compressed
strict_front_matter: true

twitter:
  username: expensesapp
  card: summary_large_image

plugins:
- jekyll-seo-tag
- jekyll-sitemap

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
