name: Upadte eurofxref

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-eurofxref:
    runs-on: macos-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3

    - name: Update eurofxref
      run: ./scripts/update-eurofxref.swift ${{ secrets.FIXER_API_KEY }}

    - name: Push update
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Hiroki Nagasawa'
          git config --global user.email '2482478+pixyzehn@users.noreply.github.com'
          git commit -am "Update eurofxref XML file"
          git push
        fi
